from pathlib import Path
p=Path('app/src/main/java/com/openai/rippledemo/MainActivity.java')
s=p.read_text(encoding='utf-8')
def rep(a,b,n):
    global s
    if a not in s: raise SystemExit('missing '+n)
    s=s.replace(a,b,1)
rep('import android.app.KeyguardManager;\n','import android.app.KeyguardManager;\nimport android.app.ActivityOptions;\nimport android.app.role.RoleManager;\n','app imports')
rep('import android.content.Context;\n','import android.content.Context;\nimport android.content.BroadcastReceiver;\nimport android.content.ComponentName;\nimport android.content.IntentFilter;\n','content imports')
rep('import android.content.SharedPreferences;\n','import android.content.SharedPreferences;\nimport android.content.pm.PackageManager;\nimport android.content.pm.ResolveInfo;\n','pm imports')
rep('import android.graphics.drawable.Drawable;\n','import android.graphics.drawable.Drawable;\nimport android.graphics.drawable.ColorDrawable;\n','drawable import')
rep('    private boolean launchedOverKeyguard;\n','    private boolean launchedOverKeyguard;\n    private boolean launchedAsHome;\n    private static volatile boolean homeSessionUnlocked=false;\n    private static volatile boolean sessionReceiverRegistered=false;\n','activity fields')
rep('''        KeyguardManager km = (KeyguardManager) getSystemService(Context.KEYGUARD_SERVICE);\n        launchedOverKeyguard = km != null && km.isKeyguardLocked();\n\n        lockView = new RippleLockView();\n''','''        KeyguardManager km = (KeyguardManager) getSystemService(Context.KEYGUARD_SERVICE);\n        launchedOverKeyguard = km != null && km.isKeyguardLocked();\n        launchedAsHome = getIntent()!=null && getIntent().hasCategory(Intent.CATEGORY_HOME);\n        ensureSessionResetReceiver();\n        getWindow().addFlags(WindowManager.LayoutParams.FLAG_SHOW_WALLPAPER);\n        getWindow().setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));\n\n        lockView = new RippleLockView();\n''','onCreate setup')
rep('''        applyLockscreenMode(lockView.isLockscreenMode());\n        hideSystemBars();\n    }\n\n    @Override\n    protected void onResume() {\n''','''        applyLockscreenMode(lockView.isLockscreenMode());\n        hideSystemBars();\n        if(launchedAsHome && homeSessionUnlocked) lockView.post(lockView::launchConfiguredHomeAndFinish);\n    }\n\n    @Override protected void onNewIntent(Intent intent){\n        super.onNewIntent(intent); setIntent(intent);\n        launchedAsHome=intent!=null&&intent.hasCategory(Intent.CATEGORY_HOME);\n        if(lockView!=null&&launchedAsHome){if(homeSessionUnlocked)lockView.post(lockView::launchConfiguredHomeAndFinish);else lockView.forceHomeGate();}\n    }\n\n    private void ensureSessionResetReceiver(){\n        if(sessionReceiverRegistered)return;\n        synchronized(MainActivity.class){if(sessionReceiverRegistered)return;\n            getApplicationContext().registerReceiver(new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){if(Intent.ACTION_SCREEN_OFF.equals(i.getAction()))homeSessionUnlocked=false;}},new IntentFilter(Intent.ACTION_SCREEN_OFF),Context.RECEIVER_NOT_EXPORTED);\n            sessionReceiverRegistered=true;\n        }\n    }\n\n    @Override\n    protected void onResume() {\n''','activity lifecycle')
rep('        private static final String KEY_DEBUG = "debug";\n','        private static final String KEY_DEBUG = "debug";\n        private static final String KEY_HOME_TARGET = "home_target";\n','pref key')
rep('        private static final int PICK_DEBUG = 3;\n','        private static final int PICK_DEBUG = 3;\n        private static final int PICK_HOME_APP = 4;\n','picker id')
rep('        private int failFeedback;\n','        private int failFeedback;\n        private String homeTarget="";\n        private boolean homeLaunchRequested=false;\n','view fields')
rep('''            debugMode = prefs.getBoolean(KEY_DEBUG, false);\n            loadCode();\n            loadWallpaper();\n''','''            debugMode = prefs.getBoolean(KEY_DEBUG, false);\n            homeTarget=prefs.getString(KEY_HOME_TARGET,""); if(homeTarget==null)homeTarget=""; ensureHomeTarget();\n            loadCode(); wallpaperDrawable=null;\n''','constructor')
rep('        private boolean settingsAllowed() { return !launchedOverKeyguard && !keyguardShowing(); }\n','        private boolean settingsAllowed() { return !launchedAsHome && !launchedOverKeyguard && !keyguardShowing(); }\n','settings gate')
rep('            drawWallpaper(canvas, w, h, now);\n','            // Exact system wallpaper is revealed by FLAG_SHOW_WALLPAPER.\n','wallpaper draw')
insert='''        private List<ResolveInfo> homeCandidates(){Intent q=new Intent(Intent.ACTION_MAIN);q.addCategory(Intent.CATEGORY_HOME);List<ResolveInfo> all=getPackageManager().queryIntentActivities(q,PackageManager.MATCH_DEFAULT_ONLY),out=new ArrayList<>();for(ResolveInfo ri:all)if(ri.activityInfo!=null&&!getPackageName().equals(ri.activityInfo.packageName))out.add(ri);return out;}\n        private void ensureHomeTarget(){List<ResolveInfo> c=homeCandidates();boolean ok=false;for(ResolveInfo ri:c){ComponentName cn=new ComponentName(ri.activityInfo.packageName,ri.activityInfo.name);if(cn.flattenToString().equals(homeTarget)){ok=true;break;}}if(!ok&&!c.isEmpty()){ResolveInfo ri=c.get(0);homeTarget=new ComponentName(ri.activityInfo.packageName,ri.activityInfo.name).flattenToString();prefs.edit().putString(KEY_HOME_TARGET,homeTarget).apply();}}\n        private String homeTargetLabel(){ComponentName want=ComponentName.unflattenFromString(homeTarget);if(want==null)return language==LANG_KR?"선택 필요":"Select";for(ResolveInfo ri:homeCandidates()){ComponentName cn=new ComponentName(ri.activityInfo.packageName,ri.activityInfo.name);if(cn.equals(want)){CharSequence l=ri.loadLabel(getPackageManager());return l==null?ri.activityInfo.packageName:l.toString();}}return language==LANG_KR?"선택 필요":"Select";}\n        private boolean homeRoleHeld(){RoleManager rm=getSystemService(RoleManager.class);return rm!=null&&rm.isRoleAvailable(RoleManager.ROLE_HOME)&&rm.isRoleHeld(RoleManager.ROLE_HOME);}\n        private void requestHomeRole(){RoleManager rm=getSystemService(RoleManager.class);if(rm!=null&&rm.isRoleAvailable(RoleManager.ROLE_HOME)&&!rm.isRoleHeld(RoleManager.ROLE_HOME))startActivity(rm.createRequestRoleIntent(RoleManager.ROLE_HOME));}\n        private void launchConfiguredHomeAndFinish(){ensureHomeTarget();ComponentName cn=ComponentName.unflattenFromString(homeTarget);if(cn==null||getPackageName().equals(cn.getPackageName())){homeSessionUnlocked=false;return;}try{Intent i=new Intent(Intent.ACTION_MAIN);i.addCategory(Intent.CATEGORY_HOME);i.setComponent(cn);i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_RESET_TASK_IF_NEEDED);homeSessionUnlocked=true;startActivity(i,ActivityOptions.makeCustomAnimation(MainActivity.this,0,0).toBundle());MainActivity.this.finish();overridePendingTransition(0,0);}catch(Throwable t){homeSessionUnlocked=false;}}\n        private void forceHomeGate(){settingsOpen=false;pickerType=PICK_NONE;setupOpen=false;unlocked=false;unlocking=false;homeLaunchRequested=false;current.clear();invalidate();}\n\n'''
needle='        private boolean deviceSecure(){KeyguardManager km=(KeyguardManager)getSystemService(Context.KEYGUARD_SERVICE);return km!=null&&km.isDeviceSecure();}\n\n'
rep(needle,needle+insert,'home helpers')
rep('        private void beginUnlock(){settingsOpen=false;pickerType=PICK_NONE;setupOpen=false;orbState=ORB_ATTACHED_IDLE;orbPull=0;unlocking=true;unlocked=false;dismissRequested=false;systemDismissed=false;animationFinished=false;unlockStartedAt=SystemClock.uptimeMillis();postInvalidateOnAnimation();}\n','        private void beginUnlock(){settingsOpen=false;pickerType=PICK_NONE;setupOpen=false;orbState=ORB_ATTACHED_IDLE;orbPull=0;homeLaunchRequested=false;unlocking=true;unlocked=false;dismissRequested=false;systemDismissed=false;animationFinished=false;unlockStartedAt=SystemClock.uptimeMillis();postInvalidateOnAnimation();}\n','begin unlock')
rep('            if(lockscreenMode&&p>=.72f&&!dismissRequested){dismissRequested=true;post(MainActivity.this::requestSystemDismiss);}\n','            if(launchedAsHome&&p>=.90f&&!homeLaunchRequested){homeLaunchRequested=true;post(this::launchConfiguredHomeAndFinish);}\n            if(lockscreenMode&&p>=.72f&&!dismissRequested){dismissRequested=true;post(MainActivity.this::requestSystemDismiss);}\n','home launch timing')
p.write_text(s,encoding='utf-8')
print('v0.8 platform applied')
