from pathlib import Path
p=Path('app/src/main/java/com/openai/rippledemo/MainActivity.java')
s=p.read_text(encoding='utf-8')
def rep(a,b,n):
    global s
    if a not in s: raise SystemExit('missing '+n)
    s=s.replace(a,b,1)
rep('        private long panelOpenedAt = 0L;\n','        private long panelOpenedAt = 0L;\n        private boolean submitSwipeActive=false;\n        private float submitSwipeStartX,submitSwipeStartY,submitSwipeEndX,submitSwipeEndY;\n        private long submitSwipeReleasedAt=-1L;\n','swipe fields')
rep('                "uniform float4 uTouch3;\\n" +\n','                "uniform float4 uTouch3;\\n" +\n                "uniform float4 uSwipe;\\n" +\n                "uniform float uSwipeStrength;\\n" +\n','shader uniforms')
rep('                "float rippleGlow(float2 uv,float4 q,float aspect){float life=clamp(1.0-q.w,0.0,1.0);float2 d=metricDelta(uv-q.xy,aspect);float r=length(d);float target=0.012+q.w*0.078;float ring=exp(-pow((r-target)*62.0,2.0));return ring*q.z*life;}\\n" +\n','                "float rippleGlow(float2 uv,float4 q,float aspect){float life=clamp(1.0-q.w,0.0,1.0);float2 d=metricDelta(uv-q.xy,aspect);float r=length(d);float target=0.012+q.w*0.078;float ring=exp(-pow((r-target)*62.0,2.0));return ring*q.z*life;}\\n" +\n                "float2 warpSwipe(float2 uv,float4 s,float strength,float aspect){float2 a=s.xy,b=s.zw;float2 pa=metricDelta(uv-a,aspect),ba=metricDelta(b-a,aspect);float den=max(dot(ba,ba),0.00005);float h=clamp(dot(pa,ba)/den,0.0,1.0);float2 q=pa-ba*h;float r=length(q);float fall=exp(-r*r*92.0);float2 tv=float2(ba.x/max(aspect,0.001),ba.y);float tl=max(length(tv),0.001);float2 tang=tv/tl;float2 norm=float2(-tang.y,tang.x);return (norm*sin(h*10.0+uTime*4.6)*0.030+tang*0.014)*fall*strength;}\\n" +\n','swipe function')
rep('                "p.y+=uInertia*(0.070+0.028*noise(p*2.1+float2(2.7,t*0.08)));" +\n','                "float slosh=sin(uv.y*13.0+t*5.0+noise(p*3.0)*4.0);p.y+=uInertia*(0.105+0.052*noise(p*2.1+float2(2.7,t*0.08)))*(0.70+0.30*(1.0-uv.y));p.x+=uInertia*0.034*slosh*(1.0-smoothstep(0.52,1.0,uv.y));" +\n','inertia')
rep('                "p+=warpTouch(uv,uTouch0,aspect)+warpTouch(uv,uTouch1,aspect)+warpTouch(uv,uTouch2,aspect)+warpTouch(uv,uTouch3,aspect);" +\n','                "p+=warpTouch(uv,uTouch0,aspect)+warpTouch(uv,uTouch1,aspect)+warpTouch(uv,uTouch2,aspect)+warpTouch(uv,uTouch3,aspect)+warpSwipe(uv,uSwipe,uSwipeStrength,aspect);" +\n','swipe warp')
rep('            float motion = (float) Math.pow(clamp01(p), 2.20);\n            float top = screenH * 1.075f * motion;\n            float inertia = (float) Math.pow(clamp01(p), 1.55);\n','            float motion = (float)Math.pow(clamp01(p),2.32);\n            float top = screenH*1.075f*motion;\n            float inertia = clampF((float)Math.pow(clamp01(p),1.12)*1.72f,0f,1.72f);\n','card motion')
rep('            setTouchUniforms(now,w,h);\n            paint.setShader(oilShader);','            setTouchUniforms(now,w,h);\n            oilShader.setFloatUniform("uSwipe",submitSwipeStartX/Math.max(1f,w),submitSwipeStartY/Math.max(1f,h),submitSwipeEndX/Math.max(1f,w),submitSwipeEndY/Math.max(1f,h));\n            oilShader.setFloatUniform("uSwipeStrength",swipeVisualStrength(now));\n            paint.setShader(oilShader);','swipe uniforms')
rep('                    orbState == ORB_STRETCHING || orbState == ORB_DETACHED_DRAGGING;\n','                    orbState == ORB_STRETCHING || orbState == ORB_DETACHED_DRAGGING || swipeVisualStrength(now)>0.001f;\n','animate wake')
start=s.index('        @Override public boolean onTouchEvent(MotionEvent e){')
end=s.index('        private void handleSettingRow',start)
block='''        @Override public boolean onTouchEvent(MotionEvent e){\n            if(unlocking)return true;\n            if(unlocked){if(e.getActionMasked()==MotionEvent.ACTION_DOWN&&!lockscreenMode&&!launchedAsHome){unlocked=false;dismissRequested=false;systemDismissed=false;animationFinished=false;invalidate();}return true;}\n            float x=e.getX(),y=e.getY();\n            if(settingsOpen&&settingsAllowed()){if(e.getActionMasked()==MotionEvent.ACTION_DOWN){if(pickerType!=PICK_NONE){String[] items=pickerItems();if(items!=null){for(int i=0;i<items.length;i++)if(pickerItemRect(i,getWidth(),getHeight(),items.length).contains(x,y)){applyPickerSelection(i);pickerType=PICK_NONE;invalidate();return true;}}if(!pickerRect(getWidth(),getHeight(),items==null?1:items.length).contains(x,y)){pickerType=PICK_NONE;invalidate();}return true;}if(setupOpen){for(int i=0;i<5;i++)if(setupRowRect(i,getWidth(),getHeight()).contains(x,y)){handleSetupRow(i);return true;}return true;}if(!settingsSheetRect(getWidth(),getHeight()).contains(x,y)){closeSettingsPanel();return true;}for(int i=0;i<6;i++)if(settingsRowRect(i,getWidth(),getHeight()).contains(x,y)){handleSettingRow(i);return true;}}return true;}\n            if(settingsAllowed()&&handleSettingsOrbGesture(e))return true;\n            if(e.getActionMasked()==MotionEvent.ACTION_DOWN){downX=x;downY=y;lastTrailX=x;lastTrailY=y;lastTrailAt=SystemClock.uptimeMillis();moved=false;submitSwipeActive=false;submitSwipeReleasedAt=-1L;submitSwipeStartX=x;submitSwipeStartY=y;submitSwipeEndX=x;submitSwipeEndY=y;addTouch(x,y,1.12f);if(!style().oil)classicRipples.add(new ClassicRipple(x,y,SystemClock.uptimeMillis()));postInvalidateOnAnimation();return true;}\n            if(e.getActionMasked()==MotionEvent.ACTION_MOVE){float dx=x-downX,dy=y-downY;if(dx*dx+dy*dy>swipeThreshold()*swipeThreshold())moved=true;if(moved){submitSwipeActive=true;submitSwipeEndX=x;submitSwipeEndY=y;postInvalidateOnAnimation();}else{long now=SystemClock.uptimeMillis();float tx=x-lastTrailX,ty=y-lastTrailY;if(now-lastTrailAt>52&&(tx*tx+ty*ty)>dp(14)*dp(14)){addTouch(x,y,.38f);lastTrailX=x;lastTrailY=y;lastTrailAt=now;}}return true;}\n            if(e.getActionMasked()==MotionEvent.ACTION_UP){float dx=x-downX,dy=y-downY;boolean swipe=moved||dx*dx+dy*dy>swipeThreshold()*swipeThreshold();if(swipe){submitSwipeEndX=x;submitSwipeEndY=y;submitSwipeActive=false;submitSwipeReleasedAt=SystemClock.uptimeMillis();finalizeSequence();}else current.add(zoneFor(x,y));invalidate();return true;}\n            if(e.getActionMasked()==MotionEvent.ACTION_CANCEL){moved=false;submitSwipeActive=false;submitSwipeReleasedAt=SystemClock.uptimeMillis();return true;}return true;\n        }\n\n'''
s=s[:start]+block+s[end:]
rep('        private float returnEase(float t){t=clamp01(t);return 1f-(float)Math.pow(1f-t,3.2);}\n','        private float returnEase(float t){t=clamp01(t);return 1f-(float)Math.pow(1f-t,3.2);}\n        private float easeOutCubic(float t){t=clamp01(t);return 1f-(float)Math.pow(1f-t,3f);}\n        private float swipeVisualStrength(long now){if(submitSwipeActive)return 1f;if(submitSwipeReleasedAt<0)return 0f;float q=clamp01((now-submitSwipeReleasedAt)/520f);return 1f-easeOutCubic(q);}\n','utilities')
p.write_text(s,encoding='utf-8')
print('v0.8 motion applied')
