from pathlib import Path
p=Path('app/src/main/java/com/openai/rippledemo/MainActivity.java')
s=p.read_text(encoding='utf-8')
def rep(a,b,n):
    global s
    if a not in s: raise SystemExit('missing '+n)
    s=s.replace(a,b,1)
def btw(a,b,r,n):
    global s
    i=s.find(a);j=s.find(b,i)
    if i<0 or j<0: raise SystemExit('missing '+n)
    s=s[:i]+r+s[j:]
rep('        private long panelOpenedAt = 0L;\n','        private long panelOpenedAt = 0L;\n        private boolean panelClosing=false;\n        private float panelOriginPull=0f;\n        private long setupAnimAt=0L;\n        private boolean setupClosing=false;\n        private long pickerAnimAt=0L;\n        private boolean pickerClosing=false;\n','panel fields')
rep('            updateOrbReturn(now);\n','            updateOrbReturn(now);\n            updatePanelAnimations(now);\n','panel update')
rep('                    orbState == ORB_STRETCHING || orbState == ORB_DETACHED_DRAGGING || swipeVisualStrength(now)>0.001f;\n','                    orbState == ORB_STRETCHING || orbState == ORB_DETACHED_DRAGGING || swipeVisualStrength(now)>0.001f || panelClosing || setupClosing || pickerClosing;\n','animate state')

# Settings panel: emerge from the edge orb, collapse back into it, subpage slides, popovers anchor to their row.
block=r'''        private void drawSettingsPanel(Canvas canvas,float w,float h,long now){
            float e=panelProgress(now);if(e<=0f)return;RectF target=settingsSheetRect(w,h);float ox=w-dp(10)-panelOriginPull,oy=h*.38f;float q=easeOutCubic(e);float cx=lerp(ox,target.centerX(),q),cy=lerp(oy,target.centerY(),q),bw=lerp(dp(48),target.width(),q),bh=lerp(dp(48),target.height(),q);RectF shown=new RectF(cx-bw/2,cy-bh/2,cx+bw/2,cy+bh/2);
            ui.setColor(Color.argb((int)(72*e),0,0,0));canvas.drawRect(0,0,w,h,ui);shadow.setColor(stPlate);shadow.setShadowLayer(dp(24)*e,0,dp(10)*e,Color.argb((int)(100*e),0,0,0));canvas.drawRoundRect(shown,dp(27),dp(27),shadow);shadow.clearShadowLayer();paint.setShader(new LinearGradient(shown.left,shown.top,shown.right,shown.bottom,new int[]{stPlateLight,stPlate},null,Shader.TileMode.CLAMP));canvas.drawRoundRect(shown,dp(27),dp(27),paint);paint.setShader(null);line.setStyle(Paint.Style.STROKE);line.setStrokeWidth(dp(.8f));line.setColor(Color.argb((int)(28*e),255,255,255));canvas.drawRoundRect(shown,dp(27),dp(27),line);line.setStyle(Paint.Style.FILL);
            if(e<.56f)return;int a=(int)(255*clamp01((e-.56f)/.44f));float sp=setupProgress(now);drawSettingsMain(canvas,target,w,h,a,sp);if(setupOpen||setupClosing)drawSetupAnimated(canvas,target,w,h,a,sp);if(pickerType!=PICK_NONE)drawPicker(canvas,w,h,a,now);
        }
        private void drawSettingsMain(Canvas canvas,RectF sheet,float w,float h,int a,float sp){int ma=(int)(a*(1f-.42f*sp));canvas.save();canvas.translate(-dp(22)*sp,0);text.setTextAlign(Paint.Align.LEFT);text.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);text.setTextSize(dp(20));text.setColor(Color.argb(ma,Color.red(stInk),Color.green(stInk),Color.blue(stInk)));canvas.drawText(language==LANG_KR?"설정":"Settings",sheet.left+dp(22),sheet.top+dp(38),text);text.setTypeface(android.graphics.Typeface.DEFAULT);String[] labels=language==LANG_KR?new String[]{"표면","언어","실패 피드백","디버그 모드","잠금화면 설정","Ripple Code 초기화"}:new String[]{"Surface","Language","Failure feedback","Debug mode","Lockscreen setup","Reset Ripple Code"};String[] values=new String[]{style().name,language==LANG_KR?"한국어":"English",feedbackName(),debugMode?"ON":"OFF",setupStatus(),""};for(int i=0;i<labels.length;i++){RectF r=settingsRowRect(i,w,h);ui.setColor(i==5?Color.argb((int)(24*(ma/255f)),190,95,95):Color.argb((int)(16*(ma/255f)),255,255,255));canvas.drawRoundRect(r,dp(15),dp(15),ui);text.setTextAlign(Paint.Align.LEFT);text.setTextSize(dp(14));text.setColor(Color.argb(ma,Color.red(stInk),Color.green(stInk),Color.blue(stInk)));canvas.drawText(labels[i],r.left+dp(16),r.centerY()+dp(5),text);if(i<5){text.setTextAlign(Paint.Align.RIGHT);text.setTextSize(dp(12));text.setColor(Color.argb((int)(210*(ma/255f)),Color.red(stMuted),Color.green(stMuted),Color.blue(stMuted)));canvas.drawText(values[i]+"  ›",r.right-dp(15),r.centerY()+dp(4),text);}}canvas.restore();}
        private void drawSetupAnimated(Canvas canvas,RectF sheet,float w,float h,int a,float sp){if(sp<=0f)return;int sa=(int)(a*sp);canvas.save();canvas.translate(dp(28)*(1f-sp),0);text.setTextAlign(Paint.Align.LEFT);text.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);text.setTextSize(dp(18));text.setColor(Color.argb(sa,Color.red(stInk),Color.green(stInk),Color.blue(stInk)));canvas.drawText(language==LANG_KR?"잠금화면 연결":"Lockscreen integration",sheet.left+dp(22),sheet.top+dp(38),text);text.setTypeface(android.graphics.Typeface.DEFAULT);text.setTextSize(dp(10.5f));text.setColor(Color.argb((int)(190*sp),Color.red(stMuted),Color.green(stMuted),Color.blue(stMuted)));canvas.drawText(language==LANG_KR?"지문은 Android가 처리하고 Ripple Code는 HOME 진입을 맡습니다":"Android keeps fingerprint security; Ripple Code gates HOME",sheet.left+dp(22),sheet.top+dp(58),text);String[] labels=language==LANG_KR?new String[]{"잠금화면 오버레이","HOME 브리지 (권장)","뒤에 열 홈 앱","다른 앱 위에 표시","배터리 최적화","시스템 화면 잠금","뒤로"}:new String[]{"Lockscreen overlay","HOME bridge (recommended)","Launcher behind","Display over apps","Battery optimization","System screen lock","Back"};String[] values=new String[]{lockscreenMode?"ON":"OFF",homeRoleHeld()?"ACTIVE":"SETUP",homeTargetLabel(),Settings.canDrawOverlays(MainActivity.this)?"ALLOWED":"OPTIONAL",batteryStatus(),deviceSecure()?"SECURE":"NONE",""};for(int i=0;i<labels.length;i++){RectF r=setupRowRect(i,w,h);ui.setColor(Color.argb((int)(16*sp),255,255,255));canvas.drawRoundRect(r,dp(15),dp(15),ui);text.setTextAlign(Paint.Align.LEFT);text.setTextSize(dp(12.8f));text.setColor(Color.argb(sa,Color.red(stInk),Color.green(stInk),Color.blue(stInk)));canvas.drawText(labels[i],r.left+dp(15),r.centerY()+dp(5),text);if(i<6){text.setTextAlign(Paint.Align.RIGHT);text.setTextSize(dp(10.4f));text.setColor(Color.argb((int)(195*sp),Color.red(stMuted),Color.green(stMuted),Color.blue(stMuted)));canvas.drawText(values[i]+"  ›",r.right-dp(14),r.centerY()+dp(4),text);}}canvas.restore();}
        private void drawPicker(Canvas canvas,float w,float h,int alpha,long now){String[] items=pickerItems();if(items==null)return;float q=pickerProgress(now);if(q<=0f)return;RectF box=pickerRect(w,h,items.length),anchor=pickerAnchorRect(w,h);float scale=.92f+.08f*easeOutCubic(q);canvas.save();canvas.scale(scale,scale,anchor.right,box.top);shadow.setColor(stPlateLight);shadow.setShadowLayer(dp(18)*q,0,dp(7)*q,Color.argb((int)(90*q),0,0,0));canvas.drawRoundRect(box,dp(24),dp(24),shadow);shadow.clearShadowLayer();ui.setColor(Color.argb((int)(255*q),Color.red(stPlateLight),Color.green(stPlateLight),Color.blue(stPlateLight)));canvas.drawRoundRect(box,dp(24),dp(24),ui);for(int i=0;i<items.length;i++){RectF r=pickerItemRect(i,w,h,items.length);boolean active=pickerSelection()==i;ui.setColor(active?Color.argb((int)(34*q),162,171,199):Color.TRANSPARENT);canvas.drawRoundRect(r,dp(14),dp(14),ui);text.setTextAlign(Paint.Align.LEFT);text.setTextSize(dp(14));text.setColor(Color.argb((int)(alpha*q),Color.red(stInk),Color.green(stInk),Color.blue(stInk)));canvas.drawText(items[i],r.left+dp(15),r.centerY()+dp(5),text);if(active){text.setTextAlign(Paint.Align.RIGHT);text.setColor(Color.argb((int)(alpha*q),162,171,199));canvas.drawText("✓",r.right-dp(15),r.centerY()+dp(5),text);}}canvas.restore();}

'''
btw('        private void drawSettingsPanel','        private String feedbackName',block,'panel block')

# Combined touch flow, including swipe wake from v0.8 motion.
touch=r'''        @Override public boolean onTouchEvent(MotionEvent e){
            if(unlocking)return true;if(unlocked){if(e.getActionMasked()==MotionEvent.ACTION_DOWN&&!lockscreenMode&&!launchedAsHome){unlocked=false;dismissRequested=false;systemDismissed=false;animationFinished=false;invalidate();}return true;}float x=e.getX(),y=e.getY();
            if(settingsOpen&&settingsAllowed()){if(panelClosing)return true;if(e.getActionMasked()==MotionEvent.ACTION_DOWN){if(pickerType!=PICK_NONE){String[] items=pickerItems();if(items!=null){for(int i=0;i<items.length;i++)if(pickerItemRect(i,getWidth(),getHeight(),items.length).contains(x,y)){applyPickerSelection(i);beginClosePicker();invalidate();return true;}}if(!pickerRect(getWidth(),getHeight(),items==null?1:items.length).contains(x,y))beginClosePicker();return true;}if(setupOpen||setupClosing){if(!setupClosing){for(int i=0;i<7;i++)if(setupRowRect(i,getWidth(),getHeight()).contains(x,y)){handleSetupRow(i);return true;}}return true;}if(!settingsSheetRect(getWidth(),getHeight()).contains(x,y)){closeSettingsPanel();return true;}for(int i=0;i<6;i++)if(settingsRowRect(i,getWidth(),getHeight()).contains(x,y)){handleSettingRow(i);return true;}}return true;}
            if(settingsAllowed()&&handleSettingsOrbGesture(e))return true;
            if(e.getActionMasked()==MotionEvent.ACTION_DOWN){downX=x;downY=y;lastTrailX=x;lastTrailY=y;lastTrailAt=SystemClock.uptimeMillis();moved=false;submitSwipeActive=false;submitSwipeReleasedAt=-1L;submitSwipeStartX=x;submitSwipeStartY=y;submitSwipeEndX=x;submitSwipeEndY=y;addTouch(x,y,1.12f);if(!style().oil)classicRipples.add(new ClassicRipple(x,y,SystemClock.uptimeMillis()));postInvalidateOnAnimation();return true;}
            if(e.getActionMasked()==MotionEvent.ACTION_MOVE){float dx=x-downX,dy=y-downY;if(dx*dx+dy*dy>swipeThreshold()*swipeThreshold())moved=true;if(moved){submitSwipeActive=true;submitSwipeEndX=x;submitSwipeEndY=y;postInvalidateOnAnimation();}else{long n=SystemClock.uptimeMillis();float tx=x-lastTrailX,ty=y-lastTrailY;if(n-lastTrailAt>52&&(tx*tx+ty*ty)>dp(14)*dp(14)){addTouch(x,y,.38f);lastTrailX=x;lastTrailY=y;lastTrailAt=n;}}return true;}
            if(e.getActionMasked()==MotionEvent.ACTION_UP){float dx=x-downX,dy=y-downY;boolean swipe=moved||dx*dx+dy*dy>swipeThreshold()*swipeThreshold();if(swipe){submitSwipeEndX=x;submitSwipeEndY=y;submitSwipeActive=false;submitSwipeReleasedAt=SystemClock.uptimeMillis();finalizeSequence();}else current.add(zoneFor(x,y));invalidate();return true;}if(e.getActionMasked()==MotionEvent.ACTION_CANCEL){moved=false;submitSwipeActive=false;submitSwipeReleasedAt=SystemClock.uptimeMillis();return true;}return true;
        }

'''
btw('        @Override public boolean onTouchEvent(MotionEvent e){','        private void handleSettingRow',touch,'touch block')

# Dragging the edge orb past the commit distance now opens settings immediately.
btw('        private boolean handleSettingsOrbGesture','        private void openSettingsPanel',r'''        private boolean handleSettingsOrbGesture(MotionEvent e){float x=e.getX(),y=e.getY();RectF hit=settingsOrbHitRect(getWidth(),getHeight());int a=e.getActionMasked();if(a==MotionEvent.ACTION_DOWN){if(!hit.contains(x,y))return false;orbPointerId=e.getPointerId(0);orbDownX=x;orbDownY=y;orbDownAt=SystemClock.uptimeMillis();orbGestureIsDrag=false;orbState=ORB_ATTACHED_PRESSED;return true;}if(orbPointerId<0)return false;int idx=e.findPointerIndex(orbPointerId);if(idx<0)idx=0;x=e.getX(idx);y=e.getY(idx);if(a==MotionEvent.ACTION_MOVE){float dx=x-orbDownX,dy=y-orbDownY;if(Math.hypot(dx,dy)>dp(6))orbGestureIsDrag=true;if(orbGestureIsDrag){orbPull=clampF(orbDownX-x,0,maxOrbPull());orbState=orbPull>detachThreshold()?ORB_DETACHED_DRAGGING:ORB_STRETCHING;if(orbPull>=openThreshold()){float origin=orbPull;orbPointerId=-1;openSettingsPanel(origin);return true;}invalidate();}return true;}if(a==MotionEvent.ACTION_UP||a==MotionEvent.ACTION_CANCEL){long dur=SystemClock.uptimeMillis()-orbDownAt;boolean tap=a==MotionEvent.ACTION_UP&&!orbGestureIsDrag&&dur<=350;orbPointerId=-1;if(tap){orbPull=0;openSettingsPanel(0);}else startOrbReturn();return true;}return true;}

''','orb gesture')

btw('        private void openSettingsPanel','        private void handleSettingRow',r'''        private void openSettingsPanel(float origin){settingsOpen=true;panelClosing=false;setupOpen=false;setupClosing=false;pickerType=PICK_NONE;pickerClosing=false;panelOpenedAt=SystemClock.uptimeMillis();panelOriginPull=origin;orbPull=0;orbState=ORB_PANEL_OPEN;invalidate();}
        private void closeSettingsPanel(){if(!settingsOpen||panelClosing)return;pickerType=PICK_NONE;pickerClosing=false;setupOpen=false;setupClosing=false;panelClosing=true;panelOpenedAt=SystemClock.uptimeMillis();postInvalidateOnAnimation();}
        private void startOrbReturn(){orbReturnFrom=orbPull;orbReturnStartedAt=SystemClock.uptimeMillis();orbState=ORB_RETURNING;postInvalidateOnAnimation();}
        private void updateOrbReturn(long now){if(orbState!=ORB_RETURNING)return;float q=clamp01((now-orbReturnStartedAt)/(float)ORB_RETURN_MS);orbPull=orbReturnFrom*(1f-returnEase(q));if(q>=1f){orbPull=0;orbState=ORB_ATTACHED_IDLE;}}
        private float panelProgress(long now){float q=clamp01((now-panelOpenedAt)/(float)PANEL_ANIM_MS);return panelClosing?1f-easeOutCubic(q):easeOutCubic(q);}
        private void updatePanelAnimations(long now){if(panelClosing&&now-panelOpenedAt>=PANEL_ANIM_MS){panelClosing=false;settingsOpen=false;orbState=ORB_ATTACHED_IDLE;panelOriginPull=0;}if(setupClosing&&now-setupAnimAt>=250){setupClosing=false;setupOpen=false;}if(pickerClosing&&now-pickerAnimAt>=180){pickerClosing=false;pickerType=PICK_NONE;}}
        private void openSetupPage(){setupOpen=true;setupClosing=false;setupAnimAt=SystemClock.uptimeMillis();postInvalidateOnAnimation();}
        private void closeSetupPage(){if(!setupOpen||setupClosing)return;setupClosing=true;setupAnimAt=SystemClock.uptimeMillis();postInvalidateOnAnimation();}
        private float setupProgress(long now){if(!setupOpen&&!setupClosing)return 0f;float q=clamp01((now-setupAnimAt)/250f);return setupClosing?1f-easeOutCubic(q):easeOutCubic(q);}
        private void openPicker(int type){pickerType=type;pickerClosing=false;pickerAnimAt=SystemClock.uptimeMillis();postInvalidateOnAnimation();}
        private void beginClosePicker(){if(pickerType==PICK_NONE||pickerClosing)return;pickerClosing=true;pickerAnimAt=SystemClock.uptimeMillis();postInvalidateOnAnimation();}
        private float pickerProgress(long now){if(pickerType==PICK_NONE)return 0f;float q=clamp01((now-pickerAnimAt)/180f);return pickerClosing?1f-easeOutCubic(q):easeOutCubic(q);}

''','panel state')

btw('        private void handleSettingRow','        private void openSystemSettings',r'''        private void handleSettingRow(int i){if(i==0)openPicker(PICK_SURFACE);else if(i==1)openPicker(PICK_LANGUAGE);else if(i==2)openPicker(PICK_FEEDBACK);else if(i==3)openPicker(PICK_DEBUG);else if(i==4)openSetupPage();else if(i==5){clearCode();closeSettingsPanel();}invalidate();}
        private void handleSetupRow(int i){if(i==0){lockscreenMode=!lockscreenMode;prefs.edit().putBoolean(KEY_LOCK_MODE,lockscreenMode).apply();applyLockscreenMode(lockscreenMode);}else if(i==1)requestHomeRole();else if(i==2)openPicker(PICK_HOME_APP);else if(i==3)openSystemSettings(Settings.ACTION_MANAGE_OVERLAY_PERMISSION);else if(i==4)openSystemSettings(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS);else if(i==5)openSystemSettings(Settings.ACTION_SECURITY_SETTINGS);else if(i==6)closeSetupPage();invalidate();}

''','handlers')

btw('        private String[] pickerItems()','        private void finalizeSequence()',r'''        private String[] pickerItems(){if(pickerType==PICK_SURFACE){String[] r=new String[styles.size()];for(int i=0;i<styles.size();i++)r[i]=styles.get(i).name;return r;}if(pickerType==PICK_LANGUAGE)return new String[]{"한국어","English"};if(pickerType==PICK_FEEDBACK)return language==LANG_KR?new String[]{"진동","시계 틴트"}:new String[]{"Vibration","Clock tint"};if(pickerType==PICK_DEBUG)return new String[]{"OFF","ON"};if(pickerType==PICK_HOME_APP){List<ResolveInfo> c=homeCandidates();String[] r=new String[c.size()];for(int i=0;i<c.size();i++){CharSequence l=c.get(i).loadLabel(getPackageManager());r[i]=l==null?c.get(i).activityInfo.packageName:l.toString();}return r;}return null;}
        private int pickerSelection(){if(pickerType==PICK_SURFACE)return selectedStyle;if(pickerType==PICK_LANGUAGE)return language;if(pickerType==PICK_FEEDBACK)return failFeedback;if(pickerType==PICK_DEBUG)return debugMode?1:0;if(pickerType==PICK_HOME_APP){List<ResolveInfo> c=homeCandidates();for(int i=0;i<c.size();i++){ComponentName cn=new ComponentName(c.get(i).activityInfo.packageName,c.get(i).activityInfo.name);if(cn.flattenToString().equals(homeTarget))return i;}return -1;}return 0;}
        private void applyPickerSelection(int i){if(pickerType==PICK_SURFACE){selectedStyle=clamp(i,0,styles.size()-1);prefs.edit().putInt(KEY_STYLE,selectedStyle).apply();}else if(pickerType==PICK_LANGUAGE){language=clamp(i,0,1);prefs.edit().putInt(KEY_LANG,language).apply();}else if(pickerType==PICK_FEEDBACK){failFeedback=clamp(i,0,1);prefs.edit().putInt(KEY_FEEDBACK,failFeedback).apply();}else if(pickerType==PICK_DEBUG){debugMode=i==1;prefs.edit().putBoolean(KEY_DEBUG,debugMode).apply();}else if(pickerType==PICK_HOME_APP){List<ResolveInfo> c=homeCandidates();if(i>=0&&i<c.size()){ResolveInfo ri=c.get(i);homeTarget=new ComponentName(ri.activityInfo.packageName,ri.activityInfo.name).flattenToString();prefs.edit().putString(KEY_HOME_TARGET,homeTarget).apply();}}}

''','picker methods')

rep('        private float maxOrbPull(){return Math.min(dp(230),getWidth()*.42f);}\n        private float detachThreshold(){return Math.min(dp(124),maxOrbPull()*.74f);}\n','        private float maxOrbPull(){return Math.min(dp(230),getWidth()*.42f);}\n        private float detachThreshold(){return Math.min(dp(124),maxOrbPull()*.74f);}\n        private float openThreshold(){return Math.min(dp(102),maxOrbPull()*.60f);}\n','open threshold')
rep('        private RectF setupRowRect(int i,float w,float h){RectF s=settingsSheetRect(w,h);float top=s.top+dp(78)+i*dp(58);return new RectF(s.left+dp(16),top,s.right-dp(16),top+dp(49));}\n        private RectF pickerRect(float w,float h,int count){float boxW=Math.min(w-dp(68),dp(300)),itemH=dp(49),boxH=dp(24)+count*itemH;return new RectF(w/2-boxW/2,h/2-boxH/2,w/2+boxW/2,h/2+boxH/2);}\n','        private RectF setupRowRect(int i,float w,float h){RectF s=settingsSheetRect(w,h);float top=s.top+dp(74)+i*dp(55);return new RectF(s.left+dp(16),top,s.right-dp(16),top+dp(46));}\n        private RectF pickerAnchorRect(float w,float h){if(pickerType==PICK_HOME_APP)return setupRowRect(2,w,h);int row=pickerType==PICK_SURFACE?0:pickerType==PICK_LANGUAGE?1:pickerType==PICK_FEEDBACK?2:3;return settingsRowRect(row,w,h);}\n        private RectF pickerRect(float w,float h,int count){RectF sh=settingsSheetRect(w,h),a=pickerAnchorRect(w,h);float bw=Math.min(sh.width()-dp(28),dp(286)),ih=dp(49),bh=dp(20)+count*ih,right=a.right,left=right-bw,top=a.bottom+dp(8);if(top+bh>sh.bottom-dp(12))top=a.top-dp(8)-bh;return new RectF(left,top,right,top+bh);}\n','geometry')
p.write_text(s,encoding='utf-8')
print('v0.8 settings applied')
